name: 'harvest' 

env:
  BASE_URI: 'https://linkeddata.cultureelerfgoed.nl/'
  GRAPH_ID: 'rijkscollectie-generic-graph'
  DATASET_NAME: 'rijkscollectie-rce'

on:
  workflow_dispatch: {}
    
jobs:
  harvest-data:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - uses: actions/cache@v6
      with:
        path: data/
        key: ${{ env.DATASET_NAME }}-data-cache-${{ github.run_attempt }}
    - name: Clear data/export cache
      run: |
        rm -f data/export/*
    - name: Upgrade pip and install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Harvest data from endpoint
      run: |
        python src/oai_harvester.py
    - name: print cache status
      run: ls -R
